spring:
  application:
    name: interest-connect

  datasource:
    url: jdbc:postgresql://localhost:5432/interest_connect
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000
logging:
  level:
    org.springframework.security: TRACE